version: '3.8'

services:
  widm-dashboard-end:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: widm-dashboard-end
    ports:
      - "5173:5173"
    environment:
      - VITE_END_POINT=/dash

      - VITE_API_URL=https://widm.ai-master.space/api
      - VITE_REDIRECT_URI=https://widm.ai-master.space/api/auth/return-to
      - VITE_CLIENT_ID=20240618161634J1sGMZdQrgsj

      - VITE_AUTHORITY=https://portal.ncu.edu.tw
      - VITE_TOKEN_ENDPOINT=https://portal.ncu.edu.tw/oauth2/token
      - VITE_AUTHORIZATION_ENDPOINT=https://portal.ncu.edu.tw/oauth2/authorization
      - VITE_USERINFO_ENDPOINT=https://portal.ncu.edu.tw/apis/oauth/v1/info
      
      - VITE_WEB_URL=http://widm.csie.ncu.edu.tw
      - VITE_DASHBOARD_URL=http://widm.csie.ncu.edu.tw/dash/
      

  widm-front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    container_name: widm-front-end
    ports:
      - "7230:7230"
      - "24678:24678"
    environment:
      - NEXT_PUBLIC_API_URL=https://widm.ai-master.space/api
